<?php
/**
 * AuthRegisterPostRequest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the AuthRegisterPostRequest model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class AuthRegisterPostRequest 
{
        /**
     * @var string|null
     * @SerializedName("email")
     * @Type("string")
    */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $email = null;

    /**
     * @var string|null
     * @SerializedName("password")
     * @Type("string")
    */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $password = null;

    /**
     * @var string|null
     * @SerializedName("first_name")
     * @Type("string")
    */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $firstName = null;

    /**
     * @var string|null
     * @SerializedName("last_name")
     * @Type("string")
    */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $lastName = null;

    /**
     * @var string|null
     * @SerializedName("phone_number")
     * @Type("string")
    */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $phoneNumber = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->email = array_key_exists('email', $data) ? $data['email'] : $this->email;
            $this->password = array_key_exists('password', $data) ? $data['password'] : $this->password;
            $this->firstName = array_key_exists('firstName', $data) ? $data['firstName'] : $this->firstName;
            $this->lastName = array_key_exists('lastName', $data) ? $data['lastName'] : $this->lastName;
            $this->phoneNumber = array_key_exists('phoneNumber', $data) ? $data['phoneNumber'] : $this->phoneNumber;
        }
    }

    /**
     * Gets email.
     *
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
    * Sets email.
    *
    * @param string|null $email
    *
    * @return $this
    */
    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }




    /**
     * Gets password.
     *
     * @return string|null
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
    * Sets password.
    *
    * @param string|null $password
    *
    * @return $this
    */
    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }




    /**
     * Gets firstName.
     *
     * @return string|null
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
    * Sets firstName.
    *
    * @param string|null $firstName
    *
    * @return $this
    */
    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }




    /**
     * Gets lastName.
     *
     * @return string|null
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
    * Sets lastName.
    *
    * @param string|null $lastName
    *
    * @return $this
    */
    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }




    /**
     * Gets phoneNumber.
     *
     * @return string|null
     */
    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    /**
    * Sets phoneNumber.
    *
    * @param string|null $phoneNumber
    *
    * @return $this
    */
    public function setPhoneNumber(?string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }



}


