<?php
/**
 * AuthTokenRefreshPost200Response
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the AuthTokenRefreshPost200Response model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class AuthTokenRefreshPost200Response 
{
        /**
     * @var string|null
     * @SerializedName("token")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $token = null;

    /**
     * @var string|null
     * @SerializedName("refresh_token")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $refreshToken = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->token = array_key_exists('token', $data) ? $data['token'] : $this->token;
            $this->refreshToken = array_key_exists('refreshToken', $data) ? $data['refreshToken'] : $this->refreshToken;
        }
    }

    /**
     * Gets token.
     *
     * @return string|null
     */
    public function getToken(): ?string
    {
        return $this->token;
    }

    /**
    * Sets token.
    *
    * @param string|null $token
    *
    * @return $this
    */
    public function setToken(?string $token = null): self
    {
        $this->token = $token;

        return $this;
    }




    /**
     * Gets refreshToken.
     *
     * @return string|null
     */
    public function getRefreshToken(): ?string
    {
        return $this->refreshToken;
    }

    /**
    * Sets refreshToken.
    *
    * @param string|null $refreshToken
    *
    * @return $this
    */
    public function setRefreshToken(?string $refreshToken = null): self
    {
        $this->refreshToken = $refreshToken;

        return $this;
    }



}


