<?php
/**
 * FilterOptions
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the FilterOptions model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class FilterOptions 
{
        /**
     * @var Manufacturer[]|null
     * @SerializedName("manufacturers")
     * @Type("array<OpenAPI\Server\Model\Manufacturer>")
    */
    #[Assert\All([
        new Assert\Type("OpenAPI\Server\Model\Manufacturer"),
    ])]
    protected ?array $manufacturers = null;

    /**
     * @var CarModel[]|null
     * @SerializedName("car_models")
     * @Type("array<OpenAPI\Server\Model\CarModel>")
    */
    #[Assert\All([
        new Assert\Type("OpenAPI\Server\Model\CarModel"),
    ])]
    protected ?array $carModels = null;

    /**
     * @var Color[]|null
     * @SerializedName("colors")
     * @Type("array<OpenAPI\Server\Model\Color>")
    */
    #[Assert\All([
        new Assert\Type("OpenAPI\Server\Model\Color"),
    ])]
    protected ?array $colors = null;

    /**
     * @var EngineVolume[]|null
     * @SerializedName("engine_volumes")
     * @Type("array<OpenAPI\Server\Model\EngineVolume>")
    */
    #[Assert\All([
        new Assert\Type("OpenAPI\Server\Model\EngineVolume"),
    ])]
    protected ?array $engineVolumes = null;

    /**
     * @var string[]|null
     * @SerializedName("transmissions")
     * @Type("array<string>")
    */
    #[Assert\All([
        new Assert\Choice(["Автомат", "Механика", "Робот", "Вариатор"]),
    ])]
    #[Assert\All([
        new Assert\Type("string"),
    ])]
    protected ?array $transmissions = null;

    /**
     * @var string[]|null
     * @SerializedName("drive_types")
     * @Type("array<string>")
    */
    #[Assert\All([
        new Assert\Choice(["Полный", "Передний", "Задний"]),
    ])]
    #[Assert\All([
        new Assert\Type("string"),
    ])]
    protected ?array $driveTypes = null;

    /**
     * @var int[]|null
     * @SerializedName("years")
     * @Type("array<int>")
    */
    #[Assert\All([
        new Assert\Type("int"),
    ])]
    protected ?array $years = null;

    /**
     * @var PriceRange|null
     * @SerializedName("price_range")
     * @Type("OpenAPI\Server\Model\PriceRange")
    */
    #[Assert\Type("OpenAPI\Server\Model\PriceRange")]
    protected ?PriceRange $priceRange = null;

    /**
     * @var MileageRange|null
     * @SerializedName("mileage_range")
     * @Type("OpenAPI\Server\Model\MileageRange")
    */
    #[Assert\Type("OpenAPI\Server\Model\MileageRange")]
    protected ?MileageRange $mileageRange = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->manufacturers = array_key_exists('manufacturers', $data) ? $data['manufacturers'] : $this->manufacturers;
            $this->carModels = array_key_exists('carModels', $data) ? $data['carModels'] : $this->carModels;
            $this->colors = array_key_exists('colors', $data) ? $data['colors'] : $this->colors;
            $this->engineVolumes = array_key_exists('engineVolumes', $data) ? $data['engineVolumes'] : $this->engineVolumes;
            $this->transmissions = array_key_exists('transmissions', $data) ? $data['transmissions'] : $this->transmissions;
            $this->driveTypes = array_key_exists('driveTypes', $data) ? $data['driveTypes'] : $this->driveTypes;
            $this->years = array_key_exists('years', $data) ? $data['years'] : $this->years;
            $this->priceRange = array_key_exists('priceRange', $data) ? $data['priceRange'] : $this->priceRange;
            $this->mileageRange = array_key_exists('mileageRange', $data) ? $data['mileageRange'] : $this->mileageRange;
        }
    }

    /**
     * Gets manufacturers.
     *
     * @return Manufacturer[]|null
     */
    public function getManufacturers(): ?array
    {
        return $this->manufacturers;
    }

    /**
    * Sets manufacturers.
    *
    * @param Manufacturer[]|null $manufacturers
    *
    * @return $this
    */
    public function setManufacturers(?array $manufacturers = null): self
    {
        $this->manufacturers = $manufacturers;

        return $this;
    }




    /**
     * Gets carModels.
     *
     * @return CarModel[]|null
     */
    public function getCarModels(): ?array
    {
        return $this->carModels;
    }

    /**
    * Sets carModels.
    *
    * @param CarModel[]|null $carModels
    *
    * @return $this
    */
    public function setCarModels(?array $carModels = null): self
    {
        $this->carModels = $carModels;

        return $this;
    }




    /**
     * Gets colors.
     *
     * @return Color[]|null
     */
    public function getColors(): ?array
    {
        return $this->colors;
    }

    /**
    * Sets colors.
    *
    * @param Color[]|null $colors
    *
    * @return $this
    */
    public function setColors(?array $colors = null): self
    {
        $this->colors = $colors;

        return $this;
    }




    /**
     * Gets engineVolumes.
     *
     * @return EngineVolume[]|null
     */
    public function getEngineVolumes(): ?array
    {
        return $this->engineVolumes;
    }

    /**
    * Sets engineVolumes.
    *
    * @param EngineVolume[]|null $engineVolumes
    *
    * @return $this
    */
    public function setEngineVolumes(?array $engineVolumes = null): self
    {
        $this->engineVolumes = $engineVolumes;

        return $this;
    }




    /**
     * Gets transmissions.
     *
     * @return string[]|null
     */
    public function getTransmissions(): ?array
    {
        return $this->transmissions;
    }

    /**
    * Sets transmissions.
    *
    * @param string[]|null $transmissions
    *
    * @return $this
    */
    public function setTransmissions(?array $transmissions = null): self
    {
        $this->transmissions = $transmissions;

        return $this;
    }




    /**
     * Gets driveTypes.
     *
     * @return string[]|null
     */
    public function getDriveTypes(): ?array
    {
        return $this->driveTypes;
    }

    /**
    * Sets driveTypes.
    *
    * @param string[]|null $driveTypes
    *
    * @return $this
    */
    public function setDriveTypes(?array $driveTypes = null): self
    {
        $this->driveTypes = $driveTypes;

        return $this;
    }




    /**
     * Gets years.
     *
     * @return int[]|null
     */
    public function getYears(): ?array
    {
        return $this->years;
    }

    /**
    * Sets years.
    *
    * @param int[]|null $years
    *
    * @return $this
    */
    public function setYears(?array $years = null): self
    {
        $this->years = $years;

        return $this;
    }




    /**
     * Gets priceRange.
     *
     * @return PriceRange|null
     */
    public function getPriceRange(): ?PriceRange
    {
        return $this->priceRange;
    }

    /**
    * Sets priceRange.
    *
    * @param PriceRange|null $priceRange
    *
    * @return $this
    */
    public function setPriceRange(?PriceRange $priceRange = null): self
    {
        $this->priceRange = $priceRange;

        return $this;
    }




    /**
     * Gets mileageRange.
     *
     * @return MileageRange|null
     */
    public function getMileageRange(): ?MileageRange
    {
        return $this->mileageRange;
    }

    /**
    * Sets mileageRange.
    *
    * @param MileageRange|null $mileageRange
    *
    * @return $this
    */
    public function setMileageRange(?MileageRange $mileageRange = null): self
    {
        $this->mileageRange = $mileageRange;

        return $this;
    }



}


