<?php
/**
 * LotDetail
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the LotDetail model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class LotDetail 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $id = null;

    /**
     * @var string|null
     * @SerializedName("manufacturer")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $manufacturer = null;

    /**
     * @var string|null
     * @SerializedName("model")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $model = null;

    /**
     * @var int|null
     * @SerializedName("year")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $year = null;

    /**
     * @var float|null
     * @SerializedName("price")
     * @Type("float")
    */
    #[Assert\Type("float")]
    protected ?float $price = null;

    /**
     * @var int|null
     * @SerializedName("mileage")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $mileage = null;

    /**
     * @var float|null
     * @SerializedName("engine_volume")
     * @Type("float")
    */
    #[Assert\Type("float")]
    protected ?float $engineVolume = null;

    /**
     * @var string|null
     * @SerializedName("color")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $color = null;

    /**
     * @var string|null
     * @SerializedName("transmission")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $transmission = null;

    /**
     * @var string|null
     * @SerializedName("drive")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $drive = null;

    /**
     * @var string|null
     * @SerializedName("body_number")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $bodyNumber = null;

    /**
     * @var bool|null
     * @SerializedName("is_sold")
     * @Type("bool")
    */
    #[Assert\Type("bool")]
    protected ?bool $isSold = false;

    /**
     * @var \DateTime|null
     * @SerializedName("sold_date")
     * @Type("DateTime<'Y-m-d'>")
    */
    #[Assert\Type("\DateTime")]
    protected ?\DateTime $soldDate = null;

    /**
     * @var LotDetailReview|null
     * @SerializedName("review")
     * @Type("OpenAPI\Server\Model\LotDetailReview")
    */
    #[Assert\Type("OpenAPI\Server\Model\LotDetailReview")]
    protected ?LotDetailReview $review = null;

    /**
     * @var string[]|null
     * @SerializedName("images")
     * @Type("array<string>")
    */
    #[Assert\All([
        new Assert\Type("string"),
    ])]
    protected ?array $images = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
            $this->manufacturer = array_key_exists('manufacturer', $data) ? $data['manufacturer'] : $this->manufacturer;
            $this->model = array_key_exists('model', $data) ? $data['model'] : $this->model;
            $this->year = array_key_exists('year', $data) ? $data['year'] : $this->year;
            $this->price = array_key_exists('price', $data) ? $data['price'] : $this->price;
            $this->mileage = array_key_exists('mileage', $data) ? $data['mileage'] : $this->mileage;
            $this->engineVolume = array_key_exists('engineVolume', $data) ? $data['engineVolume'] : $this->engineVolume;
            $this->color = array_key_exists('color', $data) ? $data['color'] : $this->color;
            $this->transmission = array_key_exists('transmission', $data) ? $data['transmission'] : $this->transmission;
            $this->drive = array_key_exists('drive', $data) ? $data['drive'] : $this->drive;
            $this->bodyNumber = array_key_exists('bodyNumber', $data) ? $data['bodyNumber'] : $this->bodyNumber;
            $this->isSold = array_key_exists('isSold', $data) ? $data['isSold'] : $this->isSold;
            $this->soldDate = array_key_exists('soldDate', $data) ? $data['soldDate'] : $this->soldDate;
            $this->review = array_key_exists('review', $data) ? $data['review'] : $this->review;
            $this->images = array_key_exists('images', $data) ? $data['images'] : $this->images;
        }
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
    * Sets id.
    *
    * @param int|null $id
    *
    * @return $this
    */
    public function setId(?int $id = null): self
    {
        $this->id = $id;

        return $this;
    }




    /**
     * Gets manufacturer.
     *
     * @return string|null
     */
    public function getManufacturer(): ?string
    {
        return $this->manufacturer;
    }

    /**
    * Sets manufacturer.
    *
    * @param string|null $manufacturer
    *
    * @return $this
    */
    public function setManufacturer(?string $manufacturer = null): self
    {
        $this->manufacturer = $manufacturer;

        return $this;
    }




    /**
     * Gets model.
     *
     * @return string|null
     */
    public function getModel(): ?string
    {
        return $this->model;
    }

    /**
    * Sets model.
    *
    * @param string|null $model
    *
    * @return $this
    */
    public function setModel(?string $model = null): self
    {
        $this->model = $model;

        return $this;
    }




    /**
     * Gets year.
     *
     * @return int|null
     */
    public function getYear(): ?int
    {
        return $this->year;
    }

    /**
    * Sets year.
    *
    * @param int|null $year
    *
    * @return $this
    */
    public function setYear(?int $year = null): self
    {
        $this->year = $year;

        return $this;
    }




    /**
     * Gets price.
     *
     * @return float|null
     */
    public function getPrice(): ?float
    {
        return $this->price;
    }

    /**
    * Sets price.
    *
    * @param float|null $price
    *
    * @return $this
    */
    public function setPrice(?float $price = null): self
    {
        $this->price = $price;

        return $this;
    }




    /**
     * Gets mileage.
     *
     * @return int|null
     */
    public function getMileage(): ?int
    {
        return $this->mileage;
    }

    /**
    * Sets mileage.
    *
    * @param int|null $mileage
    *
    * @return $this
    */
    public function setMileage(?int $mileage = null): self
    {
        $this->mileage = $mileage;

        return $this;
    }




    /**
     * Gets engineVolume.
     *
     * @return float|null
     */
    public function getEngineVolume(): ?float
    {
        return $this->engineVolume;
    }

    /**
    * Sets engineVolume.
    *
    * @param float|null $engineVolume
    *
    * @return $this
    */
    public function setEngineVolume(?float $engineVolume = null): self
    {
        $this->engineVolume = $engineVolume;

        return $this;
    }




    /**
     * Gets color.
     *
     * @return string|null
     */
    public function getColor(): ?string
    {
        return $this->color;
    }

    /**
    * Sets color.
    *
    * @param string|null $color
    *
    * @return $this
    */
    public function setColor(?string $color = null): self
    {
        $this->color = $color;

        return $this;
    }




    /**
     * Gets transmission.
     *
     * @return string|null
     */
    public function getTransmission(): ?string
    {
        return $this->transmission;
    }

    /**
    * Sets transmission.
    *
    * @param string|null $transmission
    *
    * @return $this
    */
    public function setTransmission(?string $transmission = null): self
    {
        $this->transmission = $transmission;

        return $this;
    }




    /**
     * Gets drive.
     *
     * @return string|null
     */
    public function getDrive(): ?string
    {
        return $this->drive;
    }

    /**
    * Sets drive.
    *
    * @param string|null $drive
    *
    * @return $this
    */
    public function setDrive(?string $drive = null): self
    {
        $this->drive = $drive;

        return $this;
    }




    /**
     * Gets bodyNumber.
     *
     * @return string|null
     */
    public function getBodyNumber(): ?string
    {
        return $this->bodyNumber;
    }

    /**
    * Sets bodyNumber.
    *
    * @param string|null $bodyNumber
    *
    * @return $this
    */
    public function setBodyNumber(?string $bodyNumber = null): self
    {
        $this->bodyNumber = $bodyNumber;

        return $this;
    }




    /**
     * Gets isSold.
     *
     * @return bool|null
     */
    public function isIsSold(): ?bool
    {
        return $this->isSold;
    }

    /**
    * Sets isSold.
    *
    * @param bool|null $isSold
    *
    * @return $this
    */
    public function setIsSold(?bool $isSold = null): self
    {
        $this->isSold = $isSold;

        return $this;
    }




    /**
     * Gets soldDate.
     *
     * @return \DateTime|null
     */
    public function getSoldDate(): ?\DateTime
    {
        return $this->soldDate;
    }

    /**
    * Sets soldDate.
    *
    * @param \DateTime|null $soldDate
    *
    * @return $this
    */
    public function setSoldDate(?\DateTime $soldDate = null): self
    {
        $this->soldDate = $soldDate;

        return $this;
    }




    /**
     * Gets review.
     *
     * @return LotDetailReview|null
     */
    public function getReview(): ?LotDetailReview
    {
        return $this->review;
    }

    /**
    * Sets review.
    *
    * @param LotDetailReview|null $review
    *
    * @return $this
    */
    public function setReview(?LotDetailReview $review = null): self
    {
        $this->review = $review;

        return $this;
    }




    /**
     * Gets images.
     *
     * @return string[]|null
     */
    public function getImages(): ?array
    {
        return $this->images;
    }

    /**
    * Sets images.
    *
    * @param string[]|null $images
    *
    * @return $this
    */
    public function setImages(?array $images = null): self
    {
        $this->images = $images;

        return $this;
    }



}


