<?php
/**
 * LotDetailReview
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the LotDetailReview model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class LotDetailReview 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $id = null;

    /**
     * @var int|null
     * @SerializedName("lot_id")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $lotId = null;

    /**
     * @var string|null
     * @SerializedName("manufacturer")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $manufacturer = null;

    /**
     * @var string|null
     * @SerializedName("model")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $model = null;

    /**
     * @var string|null
     * @SerializedName("first_name")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $firstName = null;

    /**
     * @var string|null
     * @SerializedName("last_name")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $lastName = null;

    /**
     * @var string|null
     * @SerializedName("avatar_url")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $avatarUrl = null;

    /**
     * @var int|null
     * @SerializedName("rating")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $rating = null;

    /**
     * @var string|null
     * @SerializedName("comment")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $comment = null;

    /**
     * @var \DateTime|null
     * @SerializedName("created_at")
     * @Type("DateTime")
    */
    #[Assert\Type("\DateTime")]
    protected ?\DateTime $createdAt = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
            $this->lotId = array_key_exists('lotId', $data) ? $data['lotId'] : $this->lotId;
            $this->manufacturer = array_key_exists('manufacturer', $data) ? $data['manufacturer'] : $this->manufacturer;
            $this->model = array_key_exists('model', $data) ? $data['model'] : $this->model;
            $this->firstName = array_key_exists('firstName', $data) ? $data['firstName'] : $this->firstName;
            $this->lastName = array_key_exists('lastName', $data) ? $data['lastName'] : $this->lastName;
            $this->avatarUrl = array_key_exists('avatarUrl', $data) ? $data['avatarUrl'] : $this->avatarUrl;
            $this->rating = array_key_exists('rating', $data) ? $data['rating'] : $this->rating;
            $this->comment = array_key_exists('comment', $data) ? $data['comment'] : $this->comment;
            $this->createdAt = array_key_exists('createdAt', $data) ? $data['createdAt'] : $this->createdAt;
        }
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
    * Sets id.
    *
    * @param int|null $id
    *
    * @return $this
    */
    public function setId(?int $id = null): self
    {
        $this->id = $id;

        return $this;
    }




    /**
     * Gets lotId.
     *
     * @return int|null
     */
    public function getLotId(): ?int
    {
        return $this->lotId;
    }

    /**
    * Sets lotId.
    *
    * @param int|null $lotId
    *
    * @return $this
    */
    public function setLotId(?int $lotId = null): self
    {
        $this->lotId = $lotId;

        return $this;
    }




    /**
     * Gets manufacturer.
     *
     * @return string|null
     */
    public function getManufacturer(): ?string
    {
        return $this->manufacturer;
    }

    /**
    * Sets manufacturer.
    *
    * @param string|null $manufacturer
    *
    * @return $this
    */
    public function setManufacturer(?string $manufacturer = null): self
    {
        $this->manufacturer = $manufacturer;

        return $this;
    }




    /**
     * Gets model.
     *
     * @return string|null
     */
    public function getModel(): ?string
    {
        return $this->model;
    }

    /**
    * Sets model.
    *
    * @param string|null $model
    *
    * @return $this
    */
    public function setModel(?string $model = null): self
    {
        $this->model = $model;

        return $this;
    }




    /**
     * Gets firstName.
     *
     * @return string|null
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
    * Sets firstName.
    *
    * @param string|null $firstName
    *
    * @return $this
    */
    public function setFirstName(?string $firstName = null): self
    {
        $this->firstName = $firstName;

        return $this;
    }




    /**
     * Gets lastName.
     *
     * @return string|null
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
    * Sets lastName.
    *
    * @param string|null $lastName
    *
    * @return $this
    */
    public function setLastName(?string $lastName = null): self
    {
        $this->lastName = $lastName;

        return $this;
    }




    /**
     * Gets avatarUrl.
     *
     * @return string|null
     */
    public function getAvatarUrl(): ?string
    {
        return $this->avatarUrl;
    }

    /**
    * Sets avatarUrl.
    *
    * @param string|null $avatarUrl
    *
    * @return $this
    */
    public function setAvatarUrl(?string $avatarUrl = null): self
    {
        $this->avatarUrl = $avatarUrl;

        return $this;
    }




    /**
     * Gets rating.
     *
     * @return int|null
     */
    public function getRating(): ?int
    {
        return $this->rating;
    }

    /**
    * Sets rating.
    *
    * @param int|null $rating
    *
    * @return $this
    */
    public function setRating(?int $rating = null): self
    {
        $this->rating = $rating;

        return $this;
    }




    /**
     * Gets comment.
     *
     * @return string|null
     */
    public function getComment(): ?string
    {
        return $this->comment;
    }

    /**
    * Sets comment.
    *
    * @param string|null $comment
    *
    * @return $this
    */
    public function setComment(?string $comment = null): self
    {
        $this->comment = $comment;

        return $this;
    }




    /**
     * Gets createdAt.
     *
     * @return \DateTime|null
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
    * Sets createdAt.
    *
    * @param \DateTime|null $createdAt
    *
    * @return $this
    */
    public function setCreatedAt(?\DateTime $createdAt = null): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }



}


