<?php
/**
 * LotShort
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the LotShort model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class LotShort 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $id = null;

    /**
     * @var string|null
     * @SerializedName("manufacturer")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $manufacturer = null;

    /**
     * @var string|null
     * @SerializedName("model")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $model = null;

    /**
     * @var int|null
     * @SerializedName("year")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $year = null;

    /**
     * @var string|null
     * @SerializedName("body_number")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $bodyNumber = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
            $this->manufacturer = array_key_exists('manufacturer', $data) ? $data['manufacturer'] : $this->manufacturer;
            $this->model = array_key_exists('model', $data) ? $data['model'] : $this->model;
            $this->year = array_key_exists('year', $data) ? $data['year'] : $this->year;
            $this->bodyNumber = array_key_exists('bodyNumber', $data) ? $data['bodyNumber'] : $this->bodyNumber;
        }
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
    * Sets id.
    *
    * @param int|null $id
    *
    * @return $this
    */
    public function setId(?int $id = null): self
    {
        $this->id = $id;

        return $this;
    }




    /**
     * Gets manufacturer.
     *
     * @return string|null
     */
    public function getManufacturer(): ?string
    {
        return $this->manufacturer;
    }

    /**
    * Sets manufacturer.
    *
    * @param string|null $manufacturer
    *
    * @return $this
    */
    public function setManufacturer(?string $manufacturer = null): self
    {
        $this->manufacturer = $manufacturer;

        return $this;
    }




    /**
     * Gets model.
     *
     * @return string|null
     */
    public function getModel(): ?string
    {
        return $this->model;
    }

    /**
    * Sets model.
    *
    * @param string|null $model
    *
    * @return $this
    */
    public function setModel(?string $model = null): self
    {
        $this->model = $model;

        return $this;
    }




    /**
     * Gets year.
     *
     * @return int|null
     */
    public function getYear(): ?int
    {
        return $this->year;
    }

    /**
    * Sets year.
    *
    * @param int|null $year
    *
    * @return $this
    */
    public function setYear(?int $year = null): self
    {
        $this->year = $year;

        return $this;
    }




    /**
     * Gets bodyNumber.
     *
     * @return string|null
     */
    public function getBodyNumber(): ?string
    {
        return $this->bodyNumber;
    }

    /**
    * Sets bodyNumber.
    *
    * @param string|null $bodyNumber
    *
    * @return $this
    */
    public function setBodyNumber(?string $bodyNumber = null): self
    {
        $this->bodyNumber = $bodyNumber;

        return $this;
    }



}


