<?php
/**
 * PriceRange
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the PriceRange model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class PriceRange 
{
        /**
     * @var float|null
     * @SerializedName("min")
     * @Type("float")
    */
    #[Assert\Type("float")]
    protected ?float $min = null;

    /**
     * @var float|null
     * @SerializedName("max")
     * @Type("float")
    */
    #[Assert\Type("float")]
    protected ?float $max = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->min = array_key_exists('min', $data) ? $data['min'] : $this->min;
            $this->max = array_key_exists('max', $data) ? $data['max'] : $this->max;
        }
    }

    /**
     * Gets min.
     *
     * @return float|null
     */
    public function getMin(): ?float
    {
        return $this->min;
    }

    /**
    * Sets min.
    *
    * @param float|null $min
    *
    * @return $this
    */
    public function setMin(?float $min = null): self
    {
        $this->min = $min;

        return $this;
    }




    /**
     * Gets max.
     *
     * @return float|null
     */
    public function getMax(): ?float
    {
        return $this->max;
    }

    /**
    * Sets max.
    *
    * @param float|null $max
    *
    * @return $this
    */
    public function setMax(?float $max = null): self
    {
        $this->max = $max;

        return $this;
    }



}


