<?php
/**
 * Profile
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Profile model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class Profile 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $id = null;

    /**
     * @var string|null
     * @SerializedName("first_name")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $firstName = null;

    /**
     * @var string|null
     * @SerializedName("last_name")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $lastName = null;

    /**
     * @var string|null
     * @SerializedName("phone_number")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $phoneNumber = null;

    /**
     * @var string|null
     * @SerializedName("avatar_url")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $avatarUrl = null;

    /**
     * @var int|null
     * @SerializedName("active_requests_count")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $activeRequestsCount = null;

    /**
     * @var bool|null
     * @SerializedName("is_admin")
     * @Type("bool")
    */
    #[Assert\Type("bool")]
    protected ?bool $isAdmin = false;

    /**
     * @var string|null
     * @SerializedName("email")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $email = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
            $this->firstName = array_key_exists('firstName', $data) ? $data['firstName'] : $this->firstName;
            $this->lastName = array_key_exists('lastName', $data) ? $data['lastName'] : $this->lastName;
            $this->phoneNumber = array_key_exists('phoneNumber', $data) ? $data['phoneNumber'] : $this->phoneNumber;
            $this->avatarUrl = array_key_exists('avatarUrl', $data) ? $data['avatarUrl'] : $this->avatarUrl;
            $this->activeRequestsCount = array_key_exists('activeRequestsCount', $data) ? $data['activeRequestsCount'] : $this->activeRequestsCount;
            $this->isAdmin = array_key_exists('isAdmin', $data) ? $data['isAdmin'] : $this->isAdmin;
            $this->email = array_key_exists('email', $data) ? $data['email'] : $this->email;
        }
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
    * Sets id.
    *
    * @param int|null $id
    *
    * @return $this
    */
    public function setId(?int $id = null): self
    {
        $this->id = $id;

        return $this;
    }




    /**
     * Gets firstName.
     *
     * @return string|null
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
    * Sets firstName.
    *
    * @param string|null $firstName
    *
    * @return $this
    */
    public function setFirstName(?string $firstName = null): self
    {
        $this->firstName = $firstName;

        return $this;
    }




    /**
     * Gets lastName.
     *
     * @return string|null
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
    * Sets lastName.
    *
    * @param string|null $lastName
    *
    * @return $this
    */
    public function setLastName(?string $lastName = null): self
    {
        $this->lastName = $lastName;

        return $this;
    }




    /**
     * Gets phoneNumber.
     *
     * @return string|null
     */
    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    /**
    * Sets phoneNumber.
    *
    * @param string|null $phoneNumber
    *
    * @return $this
    */
    public function setPhoneNumber(?string $phoneNumber = null): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }




    /**
     * Gets avatarUrl.
     *
     * @return string|null
     */
    public function getAvatarUrl(): ?string
    {
        return $this->avatarUrl;
    }

    /**
    * Sets avatarUrl.
    *
    * @param string|null $avatarUrl
    *
    * @return $this
    */
    public function setAvatarUrl(?string $avatarUrl = null): self
    {
        $this->avatarUrl = $avatarUrl;

        return $this;
    }




    /**
     * Gets activeRequestsCount.
     *
     * @return int|null
     */
    public function getActiveRequestsCount(): ?int
    {
        return $this->activeRequestsCount;
    }

    /**
    * Sets activeRequestsCount.
    *
    * @param int|null $activeRequestsCount
    *
    * @return $this
    */
    public function setActiveRequestsCount(?int $activeRequestsCount = null): self
    {
        $this->activeRequestsCount = $activeRequestsCount;

        return $this;
    }




    /**
     * Gets isAdmin.
     *
     * @return bool|null
     */
    public function isIsAdmin(): ?bool
    {
        return $this->isAdmin;
    }

    /**
    * Sets isAdmin.
    *
    * @param bool|null $isAdmin
    *
    * @return $this
    */
    public function setIsAdmin(?bool $isAdmin = null): self
    {
        $this->isAdmin = $isAdmin;

        return $this;
    }




    /**
     * Gets email.
     *
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
    * Sets email.
    *
    * @param string|null $email
    *
    * @return $this
    */
    public function setEmail(?string $email = null): self
    {
        $this->email = $email;

        return $this;
    }



}


