<?php
/**
 * ProfileResponse
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ProfileResponse model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class ProfileResponse 
{
        /**
     * @var Profile|null
     * @SerializedName("user")
     * @Type("OpenAPI\Server\Model\Profile")
    */
    #[Assert\Type("OpenAPI\Server\Model\Profile")]
    protected ?Profile $user = null;

    /**
     * @var Request[]|null
     * @SerializedName("requests")
     * @Type("array<OpenAPI\Server\Model\Request>")
    */
    #[Assert\All([
        new Assert\Type("OpenAPI\Server\Model\Request"),
    ])]
    protected ?array $requests = null;

    /**
     * @var LotShort[]|null
     * @SerializedName("available_lots")
     * @Type("array<OpenAPI\Server\Model\LotShort>")
    */
    #[Assert\All([
        new Assert\Type("OpenAPI\Server\Model\LotShort"),
    ])]
    protected ?array $availableLots = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->user = array_key_exists('user', $data) ? $data['user'] : $this->user;
            $this->requests = array_key_exists('requests', $data) ? $data['requests'] : $this->requests;
            $this->availableLots = array_key_exists('availableLots', $data) ? $data['availableLots'] : $this->availableLots;
        }
    }

    /**
     * Gets user.
     *
     * @return Profile|null
     */
    public function getUser(): ?Profile
    {
        return $this->user;
    }

    /**
    * Sets user.
    *
    * @param Profile|null $user
    *
    * @return $this
    */
    public function setUser(?Profile $user = null): self
    {
        $this->user = $user;

        return $this;
    }




    /**
     * Gets requests.
     *
     * @return Request[]|null
     */
    public function getRequests(): ?array
    {
        return $this->requests;
    }

    /**
    * Sets requests.
    *
    * @param Request[]|null $requests
    *
    * @return $this
    */
    public function setRequests(?array $requests = null): self
    {
        $this->requests = $requests;

        return $this;
    }




    /**
     * Gets availableLots.
     *
     * @return LotShort[]|null
     */
    public function getAvailableLots(): ?array
    {
        return $this->availableLots;
    }

    /**
    * Sets availableLots.
    *
    * @param LotShort[]|null $availableLots
    *
    * @return $this
    */
    public function setAvailableLots(?array $availableLots = null): self
    {
        $this->availableLots = $availableLots;

        return $this;
    }



}


