<?php
/**
 * RequestsPostRequest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the RequestsPostRequest model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class RequestsPostRequest 
{
        /**
     * @var string|null
     * @SerializedName("car_name")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $carName = null;

    /**
     * @var string|null
     * @SerializedName("call_time")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $callTime = null;

    /**
     * @var string|null
     * @SerializedName("comment")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $comment = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->carName = array_key_exists('carName', $data) ? $data['carName'] : $this->carName;
            $this->callTime = array_key_exists('callTime', $data) ? $data['callTime'] : $this->callTime;
            $this->comment = array_key_exists('comment', $data) ? $data['comment'] : $this->comment;
        }
    }

    /**
     * Gets carName.
     *
     * @return string|null
     */
    public function getCarName(): ?string
    {
        return $this->carName;
    }

    /**
    * Sets carName.
    *
    * @param string|null $carName
    *
    * @return $this
    */
    public function setCarName(?string $carName = null): self
    {
        $this->carName = $carName;

        return $this;
    }




    /**
     * Gets callTime.
     *
     * @return string|null
     */
    public function getCallTime(): ?string
    {
        return $this->callTime;
    }

    /**
    * Sets callTime.
    *
    * @param string|null $callTime
    *
    * @return $this
    */
    public function setCallTime(?string $callTime = null): self
    {
        $this->callTime = $callTime;

        return $this;
    }




    /**
     * Gets comment.
     *
     * @return string|null
     */
    public function getComment(): ?string
    {
        return $this->comment;
    }

    /**
    * Sets comment.
    *
    * @param string|null $comment
    *
    * @return $this
    */
    public function setComment(?string $comment = null): self
    {
        $this->comment = $comment;

        return $this;
    }



}


