<?php
/**
 * Request
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Request model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class Request 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $id = null;

    /**
     * @var string|null
     * @SerializedName("car_name")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $carName = null;

    /**
     * @var RequestLot|null
     * @SerializedName("lot")
     * @Type("OpenAPI\Server\Model\RequestLot")
    */
    #[Assert\Type("OpenAPI\Server\Model\RequestLot")]
    protected ?RequestLot $lot = null;

    /**
     * @var string|null
     * @SerializedName("call_time")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $callTime = null;

    /**
     * @var string|null
     * @SerializedName("comment")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $comment = null;

    /**
     * @var bool|null
     * @SerializedName("is_solved")
     * @Type("bool")
    */
    #[Assert\Type("bool")]
    protected ?bool $isSolved = false;

    /**
     * @var \DateTime|null
     * @SerializedName("created_at")
     * @Type("DateTime")
    */
    #[Assert\Type("\DateTime")]
    protected ?\DateTime $createdAt = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->id = array_key_exists('id', $data) ? $data['id'] : $this->id;
            $this->carName = array_key_exists('carName', $data) ? $data['carName'] : $this->carName;
            $this->lot = array_key_exists('lot', $data) ? $data['lot'] : $this->lot;
            $this->callTime = array_key_exists('callTime', $data) ? $data['callTime'] : $this->callTime;
            $this->comment = array_key_exists('comment', $data) ? $data['comment'] : $this->comment;
            $this->isSolved = array_key_exists('isSolved', $data) ? $data['isSolved'] : $this->isSolved;
            $this->createdAt = array_key_exists('createdAt', $data) ? $data['createdAt'] : $this->createdAt;
        }
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
    * Sets id.
    *
    * @param int|null $id
    *
    * @return $this
    */
    public function setId(?int $id = null): self
    {
        $this->id = $id;

        return $this;
    }




    /**
     * Gets carName.
     *
     * @return string|null
     */
    public function getCarName(): ?string
    {
        return $this->carName;
    }

    /**
    * Sets carName.
    *
    * @param string|null $carName
    *
    * @return $this
    */
    public function setCarName(?string $carName = null): self
    {
        $this->carName = $carName;

        return $this;
    }




    /**
     * Gets lot.
     *
     * @return RequestLot|null
     */
    public function getLot(): ?RequestLot
    {
        return $this->lot;
    }

    /**
    * Sets lot.
    *
    * @param RequestLot|null $lot
    *
    * @return $this
    */
    public function setLot(?RequestLot $lot = null): self
    {
        $this->lot = $lot;

        return $this;
    }




    /**
     * Gets callTime.
     *
     * @return string|null
     */
    public function getCallTime(): ?string
    {
        return $this->callTime;
    }

    /**
    * Sets callTime.
    *
    * @param string|null $callTime
    *
    * @return $this
    */
    public function setCallTime(?string $callTime = null): self
    {
        $this->callTime = $callTime;

        return $this;
    }




    /**
     * Gets comment.
     *
     * @return string|null
     */
    public function getComment(): ?string
    {
        return $this->comment;
    }

    /**
    * Sets comment.
    *
    * @param string|null $comment
    *
    * @return $this
    */
    public function setComment(?string $comment = null): self
    {
        $this->comment = $comment;

        return $this;
    }




    /**
     * Gets isSolved.
     *
     * @return bool|null
     */
    public function isIsSolved(): ?bool
    {
        return $this->isSolved;
    }

    /**
    * Sets isSolved.
    *
    * @param bool|null $isSolved
    *
    * @return $this
    */
    public function setIsSolved(?bool $isSolved = null): self
    {
        $this->isSolved = $isSolved;

        return $this;
    }




    /**
     * Gets createdAt.
     *
     * @return \DateTime|null
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
    * Sets createdAt.
    *
    * @param \DateTime|null $createdAt
    *
    * @return $this
    */
    public function setCreatedAt(?\DateTime $createdAt = null): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }



}


