<?php
/**
 * RequestsIdPatchRequest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the RequestsIdPatchRequest model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class RequestsIdPatchRequest 
{
        /**
     * @var string|null
     * @SerializedName("comment")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $comment = null;

    /**
     * @var bool|null
     * @SerializedName("is_solved")
     * @Type("bool")
    */
    #[Assert\Type("bool")]
    protected ?bool $isSolved = null;

    /**
     * @var int|null
     * @SerializedName("lot_id")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $lotId = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        if (is_array($data)) {
            $this->comment = array_key_exists('comment', $data) ? $data['comment'] : $this->comment;
            $this->isSolved = array_key_exists('isSolved', $data) ? $data['isSolved'] : $this->isSolved;
            $this->lotId = array_key_exists('lotId', $data) ? $data['lotId'] : $this->lotId;
        }
    }

    /**
     * Gets comment.
     *
     * @return string|null
     */
    public function getComment(): ?string
    {
        return $this->comment;
    }

    /**
    * Sets comment.
    *
    * @param string|null $comment
    *
    * @return $this
    */
    public function setComment(?string $comment = null): self
    {
        $this->comment = $comment;

        return $this;
    }




    /**
     * Gets isSolved.
     *
     * @return bool|null
     */
    public function isIsSolved(): ?bool
    {
        return $this->isSolved;
    }

    /**
    * Sets isSolved.
    *
    * @param bool|null $isSolved
    *
    * @return $this
    */
    public function setIsSolved(?bool $isSolved = null): self
    {
        $this->isSolved = $isSolved;

        return $this;
    }




    /**
     * Gets lotId.
     *
     * @return int|null
     */
    public function getLotId(): ?int
    {
        return $this->lotId;
    }

    /**
    * Sets lotId.
    *
    * @param int|null $lotId
    *
    * @return $this
    */
    public function setLotId(?int $lotId = null): self
    {
        $this->lotId = $lotId;

        return $this;
    }



}


