nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['http://localhost:3001']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link', 'X-New-Auth-Token']
        max_age: 3600
    paths:
        '^/': null
