<?php
/**
 * AdminApiInterfaceTest
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Api
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Server\Tests\Api;

use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * AdminApiInterfaceTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Api
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Api\AdminApiInterface
 */
class AdminApiInterfaceTest extends WebTestCase
{
    private static ?KernelBrowser $client = null;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        if (null === self::$client) {
            self::$client = static::createClient();
        }
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
        static::ensureKernelShutdown();
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for adminCatalogCreatePost
     *
     * .
     *
     */
    public function testAdminCatalogCreatePost(): void
    {
        $client = self::$client;

        $path = '/admin/catalog/create';

        $crawler = $client->request('POST', $path, [], [], ['CONTENT_TYPE' => 'application/json']);
        $this->markTestSkipped('Test for adminCatalogCreatePost not implemented');
    }

    /**
     * Test case for adminRequestsGet
     *
     * .
     *
     */
    public function testAdminRequestsGet(): void
    {
        $client = self::$client;

        $path = '/admin/requests';

        $crawler = $client->request('GET', $path);
        $this->markTestSkipped('Test for adminRequestsGet not implemented');
    }

    /**
     * Test case for adminRequestsIdDelete
     *
     * .
     *
     */
    public function testAdminRequestsIdDelete(): void
    {
        $client = self::$client;

        $path = '/admin/requests/{id}';
        $pattern = '{id}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('DELETE', $path);
        $this->markTestSkipped('Test for adminRequestsIdDelete not implemented');
    }

    /**
     * Test case for adminRequestsIdPatch
     *
     * .
     *
     */
    public function testAdminRequestsIdPatch(): void
    {
        $client = self::$client;

        $path = '/admin/requests/{id}';
        $pattern = '{id}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('PATCH', $path, [], [], ['CONTENT_TYPE' => 'application/json']);
        $this->markTestSkipped('Test for adminRequestsIdPatch not implemented');
    }

    /**
     * Test case for adminUsersGet
     *
     * .
     *
     */
    public function testAdminUsersGet(): void
    {
        $client = self::$client;

        $path = '/admin/users';

        $crawler = $client->request('GET', $path);
        $this->markTestSkipped('Test for adminUsersGet not implemented');
    }

    /**
     * Test case for adminUsersIdDelete
     *
     * .
     *
     */
    public function testAdminUsersIdDelete(): void
    {
        $client = self::$client;

        $path = '/admin/users/{id}';
        $pattern = '{id}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('DELETE', $path);
        $this->markTestSkipped('Test for adminUsersIdDelete not implemented');
    }

    /**
     * Test case for adminUsersIdGet
     *
     * .
     *
     */
    public function testAdminUsersIdGet(): void
    {
        $client = self::$client;

        $path = '/admin/users/{id}';
        $pattern = '{id}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('GET', $path);
        $this->markTestSkipped('Test for adminUsersIdGet not implemented');
    }

    /**
     * Test case for catalogIdDelete
     *
     * .
     *
     */
    public function testCatalogIdDelete(): void
    {
        $client = self::$client;

        $path = '/catalog/{id}';
        $pattern = '{id}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('DELETE', $path);
        $this->markTestSkipped('Test for catalogIdDelete not implemented');
    }

    /**
     * Test case for catalogIdUpdatePatch
     *
     * .
     *
     */
    public function testCatalogIdUpdatePatch(): void
    {
        $client = self::$client;

        $path = '/catalog/{id}/update';
        $pattern = '{id}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('PATCH', $path, [], [], ['CONTENT_TYPE' => 'application/json']);
        $this->markTestSkipped('Test for catalogIdUpdatePatch not implemented');
    }

    /**
     * @param string $regexp
     * @return mixed
     */
    protected function genTestData(string $regexp)
    {
        $grammar  = new \Hoa\File\Read('hoa://Library/Regex/Grammar.pp');
        $compiler = \Hoa\Compiler\Llk\Llk::load($grammar);
        $ast      = $compiler->parse($regexp);
        $generator = new \Hoa\Regex\Visitor\Isotropic(new \Hoa\Math\Sampler\Random());

        return $generator->visit($ast);
    }
}
