<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260602145116 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE background (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mileage INT NOT NULL, is_repainted BOOLEAN DEFAULT NULL, lot_id INT NOT NULL, color_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BC68B450A8CBA5F7 ON background (lot_id)');
        $this->addSql('CREATE INDEX IDX_BC68B4507ADA1FB5 ON background (color_id)');
        $this->addSql('CREATE TABLE car_media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path TEXT NOT NULL, lot_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B58724DBA8CBA5F7 ON car_media (lot_id)');
        $this->addSql('CREATE TABLE car_model (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, manufacturer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_83EF70EA23B42D ON car_model (manufacturer_id)');
        $this->addSql('CREATE TABLE color (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(30) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE engine_volume (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, volume NUMERIC(3, 1) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE lot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price NUMERIC(15, 2) NOT NULL, sold_date DATE DEFAULT NULL, body_number VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modification_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B81291B4A605127 ON lot (modification_id)');
        $this->addSql('CREATE TABLE manufacturer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE modification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, production_year DATE NOT NULL, drive VARCHAR(20) NOT NULL, transmission VARCHAR(50) NOT NULL, model_id INT NOT NULL, engine_volume_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF6425D27975B7E7 ON modification (model_id)');
        $this->addSql('CREATE INDEX IDX_EF6425D2A1B6F1E0 ON modification (engine_volume_id)');
        $this->addSql('CREATE TABLE profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, phone_number VARCHAR(20) NOT NULL, account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8157AA0F9B6B5FBA ON profile (account_id)');
        $this->addSql('CREATE TABLE request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, car_name VARCHAR(255) NOT NULL, call_time DATE DEFAULT NULL, comment TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, car_model_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3B978F9FF64382E3 ON request (car_model_id)');
        $this->addSql('CREATE TABLE request_user (request_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (request_id, user_id))');
        $this->addSql('CREATE INDEX IDX_F234F1B3427EB8A5 ON request_user (request_id)');
        $this->addSql('CREATE INDEX IDX_F234F1B3A76ED395 ON request_user (user_id)');
        $this->addSql('CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating SMALLINT NOT NULL, comment TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, lot_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_794381C69B6B5FBA ON review (account_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_794381C6A8CBA5F7 ON review (lot_id)');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password TEXT NOT NULL, is_verified BOOLEAN NOT NULL, role_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D649D60322AC ON "user" (role_id)');
        $this->addSql('CREATE TABLE verification_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(10) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E821C39F9B6B5FBA ON verification_code (account_id)');
        $this->addSql('ALTER TABLE background ADD CONSTRAINT FK_BC68B450A8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lot (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE background ADD CONSTRAINT FK_BC68B4507ADA1FB5 FOREIGN KEY (color_id) REFERENCES color (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE car_media ADD CONSTRAINT FK_B58724DBA8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lot (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE car_model ADD CONSTRAINT FK_83EF70EA23B42D FOREIGN KEY (manufacturer_id) REFERENCES manufacturer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lot ADD CONSTRAINT FK_B81291B4A605127 FOREIGN KEY (modification_id) REFERENCES modification (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE modification ADD CONSTRAINT FK_EF6425D27975B7E7 FOREIGN KEY (model_id) REFERENCES car_model (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE modification ADD CONSTRAINT FK_EF6425D2A1B6F1E0 FOREIGN KEY (engine_volume_id) REFERENCES engine_volume (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE profile ADD CONSTRAINT FK_8157AA0F9B6B5FBA FOREIGN KEY (account_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE request ADD CONSTRAINT FK_3B978F9FF64382E3 FOREIGN KEY (car_model_id) REFERENCES car_model (id)');
        $this->addSql('ALTER TABLE request_user ADD CONSTRAINT FK_F234F1B3427EB8A5 FOREIGN KEY (request_id) REFERENCES request (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE request_user ADD CONSTRAINT FK_F234F1B3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C69B6B5FBA FOREIGN KEY (account_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6A8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lot (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649D60322AC FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE verification_code ADD CONSTRAINT FK_E821C39F9B6B5FBA FOREIGN KEY (account_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE background DROP CONSTRAINT FK_BC68B450A8CBA5F7');
        $this->addSql('ALTER TABLE background DROP CONSTRAINT FK_BC68B4507ADA1FB5');
        $this->addSql('ALTER TABLE car_media DROP CONSTRAINT FK_B58724DBA8CBA5F7');
        $this->addSql('ALTER TABLE car_model DROP CONSTRAINT FK_83EF70EA23B42D');
        $this->addSql('ALTER TABLE lot DROP CONSTRAINT FK_B81291B4A605127');
        $this->addSql('ALTER TABLE modification DROP CONSTRAINT FK_EF6425D27975B7E7');
        $this->addSql('ALTER TABLE modification DROP CONSTRAINT FK_EF6425D2A1B6F1E0');
        $this->addSql('ALTER TABLE profile DROP CONSTRAINT FK_8157AA0F9B6B5FBA');
        $this->addSql('ALTER TABLE request DROP CONSTRAINT FK_3B978F9FF64382E3');
        $this->addSql('ALTER TABLE request_user DROP CONSTRAINT FK_F234F1B3427EB8A5');
        $this->addSql('ALTER TABLE request_user DROP CONSTRAINT FK_F234F1B3A76ED395');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C69B6B5FBA');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6A8CBA5F7');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649D60322AC');
        $this->addSql('ALTER TABLE verification_code DROP CONSTRAINT FK_E821C39F9B6B5FBA');
        $this->addSql('DROP TABLE background');
        $this->addSql('DROP TABLE car_media');
        $this->addSql('DROP TABLE car_model');
        $this->addSql('DROP TABLE color');
        $this->addSql('DROP TABLE engine_volume');
        $this->addSql('DROP TABLE lot');
        $this->addSql('DROP TABLE manufacturer');
        $this->addSql('DROP TABLE modification');
        $this->addSql('DROP TABLE profile');
        $this->addSql('DROP TABLE request');
        $this->addSql('DROP TABLE request_user');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE verification_code');
    }
}
