<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260608103448 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('ALTER TABLE request DROP CONSTRAINT fk_3b978f9fa8cba5f7');
        $this->addSql('ALTER TABLE request ADD CONSTRAINT FK_3B978F9FA8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lot (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT fk_794381c6a8cba5f7');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6A8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lot (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('ALTER TABLE request DROP CONSTRAINT FK_3B978F9FA8CBA5F7');
        $this->addSql('ALTER TABLE request ADD CONSTRAINT fk_3b978f9fa8cba5f7 FOREIGN KEY (lot_id) REFERENCES lot (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6A8CBA5F7');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT fk_794381c6a8cba5f7 FOREIGN KEY (lot_id) REFERENCES lot (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
