<?php
/**
 * AuthVerifyPostRequestTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Tests\Model;

use OpenAPI\Server\Model\AuthVerifyPostRequest;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * AuthVerifyPostRequestTest Class Doc Comment
 *
 * @category    Class
 * @description AuthVerifyPostRequest
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\AuthVerifyPostRequest
 */
class AuthVerifyPostRequestTest extends TestCase
{
    protected AuthVerifyPostRequest|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = $this->getMockBuilder(AuthVerifyPostRequest::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(AuthVerifyPostRequest::class));
        $this->assertInstanceOf(AuthVerifyPostRequest::class, $this->object);
    }

    /**
     * Test attribute "email"
     *
     * @group unit
     * @small
     */
    public function testPropertyEmail(): void
    {
        $this->markTestSkipped('Test for property email not implemented');
    }

    /**
     * Test attribute "code"
     *
     * @group unit
     * @small
     */
    public function testPropertyCode(): void
    {
        $this->markTestSkipped('Test for property code not implemented');
    }
}
