<?php
/**
 * FilterOptionsTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Tests\Model;

use OpenAPI\Server\Model\FilterOptions;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * FilterOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description FilterOptions
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\FilterOptions
 */
class FilterOptionsTest extends TestCase
{
    protected FilterOptions|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = $this->getMockBuilder(FilterOptions::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(FilterOptions::class));
        $this->assertInstanceOf(FilterOptions::class, $this->object);
    }

    /**
     * Test attribute "manufacturers"
     *
     * @group unit
     * @small
     */
    public function testPropertyManufacturers(): void
    {
        $this->markTestSkipped('Test for property manufacturers not implemented');
    }

    /**
     * Test attribute "carModels"
     *
     * @group unit
     * @small
     */
    public function testPropertyCarModels(): void
    {
        $this->markTestSkipped('Test for property carModels not implemented');
    }

    /**
     * Test attribute "colors"
     *
     * @group unit
     * @small
     */
    public function testPropertyColors(): void
    {
        $this->markTestSkipped('Test for property colors not implemented');
    }

    /**
     * Test attribute "engineVolumes"
     *
     * @group unit
     * @small
     */
    public function testPropertyEngineVolumes(): void
    {
        $this->markTestSkipped('Test for property engineVolumes not implemented');
    }

    /**
     * Test attribute "transmissions"
     *
     * @group unit
     * @small
     */
    public function testPropertyTransmissions(): void
    {
        $this->markTestSkipped('Test for property transmissions not implemented');
    }

    /**
     * Test attribute "driveTypes"
     *
     * @group unit
     * @small
     */
    public function testPropertyDriveTypes(): void
    {
        $this->markTestSkipped('Test for property driveTypes not implemented');
    }

    /**
     * Test attribute "years"
     *
     * @group unit
     * @small
     */
    public function testPropertyYears(): void
    {
        $this->markTestSkipped('Test for property years not implemented');
    }

    /**
     * Test attribute "priceRange"
     *
     * @group unit
     * @small
     */
    public function testPropertyPriceRange(): void
    {
        $this->markTestSkipped('Test for property priceRange not implemented');
    }

    /**
     * Test attribute "mileageRange"
     *
     * @group unit
     * @small
     */
    public function testPropertyMileageRange(): void
    {
        $this->markTestSkipped('Test for property mileageRange not implemented');
    }
}
