<?php
/**
 * LotDetailReviewTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Tests\Model;

use OpenAPI\Server\Model\LotDetailReview;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * LotDetailReviewTest Class Doc Comment
 *
 * @category    Class
 * @description LotDetailReview
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\LotDetailReview
 */
class LotDetailReviewTest extends TestCase
{
    protected LotDetailReview|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = $this->getMockBuilder(LotDetailReview::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(LotDetailReview::class));
        $this->assertInstanceOf(LotDetailReview::class, $this->object);
    }

    /**
     * Test attribute "id"
     *
     * @group unit
     * @small
     */
    public function testPropertyId(): void
    {
        $this->markTestSkipped('Test for property id not implemented');
    }

    /**
     * Test attribute "lotId"
     *
     * @group unit
     * @small
     */
    public function testPropertyLotId(): void
    {
        $this->markTestSkipped('Test for property lotId not implemented');
    }

    /**
     * Test attribute "manufacturer"
     *
     * @group unit
     * @small
     */
    public function testPropertyManufacturer(): void
    {
        $this->markTestSkipped('Test for property manufacturer not implemented');
    }

    /**
     * Test attribute "model"
     *
     * @group unit
     * @small
     */
    public function testPropertyModel(): void
    {
        $this->markTestSkipped('Test for property model not implemented');
    }

    /**
     * Test attribute "firstName"
     *
     * @group unit
     * @small
     */
    public function testPropertyFirstName(): void
    {
        $this->markTestSkipped('Test for property firstName not implemented');
    }

    /**
     * Test attribute "lastName"
     *
     * @group unit
     * @small
     */
    public function testPropertyLastName(): void
    {
        $this->markTestSkipped('Test for property lastName not implemented');
    }

    /**
     * Test attribute "avatarUrl"
     *
     * @group unit
     * @small
     */
    public function testPropertyAvatarUrl(): void
    {
        $this->markTestSkipped('Test for property avatarUrl not implemented');
    }

    /**
     * Test attribute "rating"
     *
     * @group unit
     * @small
     */
    public function testPropertyRating(): void
    {
        $this->markTestSkipped('Test for property rating not implemented');
    }

    /**
     * Test attribute "comment"
     *
     * @group unit
     * @small
     */
    public function testPropertyComment(): void
    {
        $this->markTestSkipped('Test for property comment not implemented');
    }

    /**
     * Test attribute "createdAt"
     *
     * @group unit
     * @small
     */
    public function testPropertyCreatedAt(): void
    {
        $this->markTestSkipped('Test for property createdAt not implemented');
    }
}
