<?php
/**
 * ProfileTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Tests\Model;

use OpenAPI\Server\Model\Profile;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * ProfileTest Class Doc Comment
 *
 * @category    Class
 * @description Profile
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\Profile
 */
class ProfileTest extends TestCase
{
    protected Profile|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = $this->getMockBuilder(Profile::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(Profile::class));
        $this->assertInstanceOf(Profile::class, $this->object);
    }

    /**
     * Test attribute "id"
     *
     * @group unit
     * @small
     */
    public function testPropertyId(): void
    {
        $this->markTestSkipped('Test for property id not implemented');
    }

    /**
     * Test attribute "email"
     *
     * @group unit
     * @small
     */
    public function testPropertyEmail(): void
    {
        $this->markTestSkipped('Test for property email not implemented');
    }

    /**
     * Test attribute "firstName"
     *
     * @group unit
     * @small
     */
    public function testPropertyFirstName(): void
    {
        $this->markTestSkipped('Test for property firstName not implemented');
    }

    /**
     * Test attribute "lastName"
     *
     * @group unit
     * @small
     */
    public function testPropertyLastName(): void
    {
        $this->markTestSkipped('Test for property lastName not implemented');
    }

    /**
     * Test attribute "phoneNumber"
     *
     * @group unit
     * @small
     */
    public function testPropertyPhoneNumber(): void
    {
        $this->markTestSkipped('Test for property phoneNumber not implemented');
    }

    /**
     * Test attribute "avatarUrl"
     *
     * @group unit
     * @small
     */
    public function testPropertyAvatarUrl(): void
    {
        $this->markTestSkipped('Test for property avatarUrl not implemented');
    }
}
