<?php
/**
 * ReviewTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Tests\Model;

use OpenAPI\Server\Model\Review;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * ReviewTest Class Doc Comment
 *
 * @category    Class
 * @description Review
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\Review
 */
class ReviewTest extends TestCase
{
    protected Review|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->object = $this->getMockBuilder(Review::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(Review::class));
        $this->assertInstanceOf(Review::class, $this->object);
    }

    /**
     * Test attribute "id"
     *
     * @group unit
     * @small
     */
    public function testPropertyId(): void
    {
        $this->markTestSkipped('Test for property id not implemented');
    }

    /**
     * Test attribute "lotId"
     *
     * @group unit
     * @small
     */
    public function testPropertyLotId(): void
    {
        $this->markTestSkipped('Test for property lotId not implemented');
    }

    /**
     * Test attribute "carName"
     *
     * @group unit
     * @small
     */
    public function testPropertyCarName(): void
    {
        $this->markTestSkipped('Test for property carName not implemented');
    }

    /**
     * Test attribute "authorName"
     *
     * @group unit
     * @small
     */
    public function testPropertyAuthorName(): void
    {
        $this->markTestSkipped('Test for property authorName not implemented');
    }

    /**
     * Test attribute "rating"
     *
     * @group unit
     * @small
     */
    public function testPropertyRating(): void
    {
        $this->markTestSkipped('Test for property rating not implemented');
    }

    /**
     * Test attribute "comment"
     *
     * @group unit
     * @small
     */
    public function testPropertyComment(): void
    {
        $this->markTestSkipped('Test for property comment not implemented');
    }

    /**
     * Test attribute "createdAt"
     *
     * @group unit
     * @small
     */
    public function testPropertyCreatedAt(): void
    {
        $this->markTestSkipped('Test for property createdAt not implemented');
    }
}
