<?php
/**
 * AdminApiInterface
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\ProfileResponse;
use OpenAPI\Server\Model\UserListItem;

/**
 * AdminApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface AdminApiInterface
{

    /**
     * Sets authentication method bearerAuth
     *
     * @param string|null $value Value of the bearerAuth authentication method.
     *
     * @return void
     */
    public function setbearerAuth(?string $value): void;

    /**
     * Operation adminUsersGet
     *
     * @param  int $page   (optional, default to 1)
     * @param  int $limit   (optional, default to 10)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function adminUsersGet(
        int $page,
        int $limit,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation adminUsersIdDelete
     *
     * @param  int $id   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function adminUsersIdDelete(
        int $id,
        int &$responseCode,
        array &$responseHeaders
    ): void;

    /**
     * Operation adminUsersIdGet
     *
     * @param  int $id   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function adminUsersIdGet(
        int $id,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;
}
