<?php
/**
 * AuthApiInterface
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\AuthChangePasswordPostRequest;
use OpenAPI\Server\Model\AuthForgotPasswordRequestPostRequest;
use OpenAPI\Server\Model\AuthForgotPasswordResetPostRequest;
use OpenAPI\Server\Model\AuthForgotPasswordVerifyPost200Response;
use OpenAPI\Server\Model\AuthForgotPasswordVerifyPostRequest;
use OpenAPI\Server\Model\AuthLoginPost200Response;
use OpenAPI\Server\Model\AuthLoginPostRequest;
use OpenAPI\Server\Model\AuthRegisterPostRequest;
use OpenAPI\Server\Model\AuthTokenRefreshPost200Response;
use OpenAPI\Server\Model\AuthTokenRefreshPostRequest;
use OpenAPI\Server\Model\AuthVerifyPostRequest;
use OpenAPI\Server\Model\AuthVerifyResendPostRequest;

/**
 * AuthApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface AuthApiInterface
{

    /**
     * Sets authentication method bearerAuth
     *
     * @param string|null $value Value of the bearerAuth authentication method.
     *
     * @return void
     */
    public function setbearerAuth(?string $value): void;

    /**
     * Operation authChangePasswordPost
     *
     * @param  AuthChangePasswordPostRequest $authChangePasswordPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function authChangePasswordPost(
        AuthChangePasswordPostRequest $authChangePasswordPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): void;

    /**
     * Operation authForgotPasswordRequestPost
     *
     * @param  AuthForgotPasswordRequestPostRequest $authForgotPasswordRequestPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function authForgotPasswordRequestPost(
        AuthForgotPasswordRequestPostRequest $authForgotPasswordRequestPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): void;

    /**
     * Operation authForgotPasswordResetPost
     *
     * @param  AuthForgotPasswordResetPostRequest $authForgotPasswordResetPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function authForgotPasswordResetPost(
        AuthForgotPasswordResetPostRequest $authForgotPasswordResetPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): void;

    /**
     * Operation authForgotPasswordVerifyPost
     *
     * @param  AuthForgotPasswordVerifyPostRequest $authForgotPasswordVerifyPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function authForgotPasswordVerifyPost(
        AuthForgotPasswordVerifyPostRequest $authForgotPasswordVerifyPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation authLoginPost
     *
     * @param  AuthLoginPostRequest $authLoginPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function authLoginPost(
        AuthLoginPostRequest $authLoginPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation authRegisterPost
     *
     * @param  AuthRegisterPostRequest $authRegisterPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function authRegisterPost(
        AuthRegisterPostRequest $authRegisterPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): void;

    /**
     * Operation authTokenRefreshPost
     *
     * @param  AuthTokenRefreshPostRequest $authTokenRefreshPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function authTokenRefreshPost(
        AuthTokenRefreshPostRequest $authTokenRefreshPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation authVerifyPost
     *
     * @param  AuthVerifyPostRequest $authVerifyPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function authVerifyPost(
        AuthVerifyPostRequest $authVerifyPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): void;

    /**
     * Operation authVerifyResendPost
     *
     * @param  AuthVerifyResendPostRequest $authVerifyResendPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function authVerifyResendPost(
        AuthVerifyResendPostRequest $authVerifyResendPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): void;
}
