<?php
/**
 * CatalogApiInterface
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\FilterOptions;
use OpenAPI\Server\Model\LotDetail;
use OpenAPI\Server\Model\LotListItem;

/**
 * CatalogApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface CatalogApiInterface
{

    /**
     * Sets authentication method bearerAuth
     *
     * @param string|null $value Value of the bearerAuth authentication method.
     *
     * @return void
     */
    public function setbearerAuth(?string $value): void;

    /**
     * Operation catalogIdDelete
     *
     * @param  int $id   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function catalogIdDelete(
        int $id,
        int &$responseCode,
        array &$responseHeaders
    ): void;

    /**
     * Operation catalogIdGet
     *
     * @param  int $id   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function catalogIdGet(
        int $id,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation catalogIdPost
     *
     * @param  int $id   (required)
     * @param  string|null $manufacturer   (optional)
     * @param  string|null $model   (optional)
     * @param  int|null $year   (optional)
     * @param  float|null $price   (optional)
     * @param  int|null $mileage   (optional)
     * @param  float|null $engineVolume   (optional)
     * @param  string|null $color   (optional)
     * @param  string|null $transmission   (optional)
     * @param  string|null $drive   (optional)
     * @param  string|null $bodyNumber   (optional)
     * @param  array|null $deletedImages   (optional)
     * @param  array|null $newImages   (optional)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function catalogIdPost(
        int $id,
        ?string $manufacturer,
        ?string $model,
        ?int $year,
        ?float $price,
        ?int $mileage,
        ?float $engineVolume,
        ?string $color,
        ?string $transmission,
        ?string $drive,
        ?string $bodyNumber,
        ?array $deletedImages,
        ?array $newImages,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation catalogPost
     *
     * @param  string|null $manufacturer   (optional)
     * @param  string|null $model   (optional)
     * @param  int|null $year   (optional)
     * @param  float|null $price   (optional)
     * @param  int|null $mileage   (optional)
     * @param  float|null $engineVolume   (optional)
     * @param  string|null $color   (optional)
     * @param  string|null $transmission   (optional)
     * @param  string|null $drive   (optional)
     * @param  string|null $bodyNumber   (optional)
     * @param  array|null $images   (optional)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function catalogPost(
        ?string $manufacturer,
        ?string $model,
        ?int $year,
        ?float $price,
        ?int $mileage,
        ?float $engineVolume,
        ?string $color,
        ?string $transmission,
        ?string $drive,
        ?string $bodyNumber,
        ?array $images,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation getCatalog
     *
     * @param  int $page   (optional, default to 1)
     * @param  int $limit   (optional, default to 10)
     * @param  string|null $search   (optional)
     * @param  int|null $manufacturerId   (optional)
     * @param  int|null $modelId   (optional)
     * @param  int|null $colorId   (optional)
     * @param  string|null $transmission   (optional)
     * @param  string|null $drive   (optional)
     * @param  int|null $year   (optional)
     * @param  float|null $priceFrom   (optional)
     * @param  float|null $priceTo   (optional)
     * @param  int|null $mileageFrom   (optional)
     * @param  int|null $mileageTo   (optional)
     * @param  int|null $engineVolumeId   (optional)
     * @param  bool|null $isSold   (optional)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function getCatalog(
        int $page,
        int $limit,
        ?string $search,
        ?int $manufacturerId,
        ?int $modelId,
        ?int $colorId,
        ?string $transmission,
        ?string $drive,
        ?int $year,
        ?float $priceFrom,
        ?float $priceTo,
        ?int $mileageFrom,
        ?int $mileageTo,
        ?int $engineVolumeId,
        ?bool $isSold,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation getCatalogFilters
     *
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function getCatalogFilters(
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;
}
