<?php
/**
 * ProfileApiInterface
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\Profile;
use OpenAPI\Server\Model\ProfileResponse;

/**
 * ProfileApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface ProfileApiInterface
{

    /**
     * Sets authentication method bearerAuth
     *
     * @param string|null $value Value of the bearerAuth authentication method.
     *
     * @return void
     */
    public function setbearerAuth(?string $value): void;

    /**
     * Operation profileGet
     *
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function profileGet(
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;

    /**
     * Operation profilePost
     *
     * @param  string|null $firstName   (optional)
     * @param  string|null $lastName   (optional)
     * @param  string|null $email   (optional)
     * @param  string|null $phoneNumber   (optional)
     * @param  UploadedFile|null $avatar   (optional)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return array|object|null
     */
    public function profilePost(
        ?string $firstName,
        ?string $lastName,
        ?string $email,
        ?string $phoneNumber,
        ?UploadedFile $avatar,
        int &$responseCode,
        array &$responseHeaders
    ): array|object|null;
}
