<?php
/**
 * RequestsApiInterface
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * cars
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use OpenAPI\Server\Model\RequestsIdPatchRequest;
use OpenAPI\Server\Model\RequestsPostRequest;

/**
 * RequestsApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  OpenAPI\Server\Api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface RequestsApiInterface
{

    /**
     * Sets authentication method bearerAuth
     *
     * @param string|null $value Value of the bearerAuth authentication method.
     *
     * @return void
     */
    public function setbearerAuth(?string $value): void;

    /**
     * Operation requestsIdDelete
     *
     * @param  int $id   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function requestsIdDelete(
        int $id,
        int &$responseCode,
        array &$responseHeaders
    ): void;

    /**
     * Operation requestsIdPatch
     *
     * @param  int $id   (required)
     * @param  RequestsIdPatchRequest|null $requestsIdPatchRequest   (optional)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function requestsIdPatch(
        int $id,
        ?RequestsIdPatchRequest $requestsIdPatchRequest,
        int &$responseCode,
        array &$responseHeaders
    ): void;

    /**
     * Operation requestsPost
     *
     * @param  RequestsPostRequest $requestsPostRequest   (required)
     * @param  int     &$responseCode    The HTTP Response Code
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     */
    public function requestsPost(
        RequestsPostRequest $requestsPostRequest,
        int &$responseCode,
        array &$responseHeaders
    ): void;
}
